/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "Tracker.h"
/* Header for class dk_itu_task_Tracker */

#ifndef _Included_dk_itu_task_Tracker
#define _Included_dk_itu_task_Tracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dk_itu_task_Tracker
 * Method:    createNativeTracker
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_dk_itu_task_Tracker_createNativeTracker
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     dk_itu_task_Tracker
 * Method:    destroyNativeTracker
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dk_itu_task_Tracker_destroyNativeTracker
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dk_itu_task_Tracker
 * Method:    initNativeTracker
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_dk_itu_task_Tracker_initNativeTracker
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dk_itu_task_Tracker
 * Method:    processNativeTracker
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_dk_itu_task_Tracker_processNativeTracker
  (JNIEnv *, jclass, jlong, jlong, jlong );

#ifdef __cplusplus
}
#endif
#endif
